### ISSUE TITLE
class tmhOAuth not found.

### ISSUE THREAD

**Issue by SalocinDotTEN** [wintercms/wn-twitter-plugin#2]
The latest Tweet component results in an error tmhoauth not found upon calling it within the page/template.

**Comment by LukeTowers** [comment]
How did you install the plugin?

**Comment by SalocinDotTEN** [comment]
Hi @LukeTowers 

It was installed using the plugin installer.

**Comment by LukeTowers** [comment]
Try installing via composer instead.

**Comment by SalocinDotTEN** [comment]
Excellent! It  works! Will close this.  👍🏽 😄
